### ISSUE TITLE
How to train

### ISSUE THREAD

**Issue by 2873238593** [HiLab-git/PyMIC_examples#1]
First of all, thank you for your work, and secondly, I would like to ask how to solve this error during training。

**Comment by 2873238593** [comment]
site-packages/pymic/transform/normalize.py", line 28, in __init__
    self.mask_enable = params['NormalizeWithMeanStd_mask'.lower()]
KeyError: 'normalizewithmeanstd_mask'

**Comment by taigw** [comment]
You should set the value of 'normalizewithmeanstd_mask' in the configure file. For example:
```
normalizewithmeanstd_mask = False
```

**Comment by 2873238593** [comment]
Thanks for your answer, the problem has been solved. I noticed that there is a part of image cropping in your network, but I didn’t find out where it is. Could you please point it out?

**Comment by taigw** [comment]
The image cropping is implemented in pymic.transform.crop
