### ISSUE TITLE
About training my own data

### ISSUE THREAD

**Issue by qiyedongcode** [HiLab-git/PyMIC_examples#9]
Really exciting work! I would like to know how to use your PyMIC to complete the semi-supervised learning of my own CT data, can you make a demo?

**Comment by taigw** [comment]
We have already provided demos for the semi-supervised learning methods. See: https://github.com/HiLab-git/PyMIC_examples/tree/main/seg_ssl/ACDC

To use your own data, just set "root_dir" and the "train_csv", "train_csv_unlab",  "valid_csv" and "test_csv" path in the configuration file, such as following:

tensor_type = float
task_type = seg
root_dir  = ../../PyMIC_data/ACDC/preprocess/
train_csv = config/data/image_train_r10_lab.csv
train_csv_unlab = config/data/image_train_r10_unlab.csv
valid_csv = config/data/image_valid.csv
test_csv  = config/data/image_test.csv

**Comment by qiyedongcode** [comment]
Thank you for your reply, can you provide some cfg files for semi-supervised learning under 3D networks and preprocessing methods for ACDC datasets

**Comment by taigw** [comment]
Thanks for your suggestion. However, the ACDC dataset has a large inter-slice spacing and it is more suitable for using 2D networks. We will consider to provide a 3D semi-supervised segmentation demo in the following.
